## Laboratorium 2
**Łukasz Rams**

8.10.2021r

piątek 9:15

**Import modułów**

In [1]:
import numpy as np
import pandas as pd

### Ćwiczenie 1

W tym ćwiczeniu należało pobrać i uporządkować przydzielony zbiór danych zgodnie z protokołem TIER oraz zasadami "tidy data".

Zbiór danych wybierany był według następującego wzoru:

$ (N\%5) +1 $

Gdzie:

$ N $ - ilość liter w nazwisku

In [2]:
# Wyznaczenie numeru zbioru danych
no = (len("Rams") % 5) + 1
"Wyznaczono zbiór danych numer %i" % no

'Wyznaczono zbiór danych numer 5'

Wyznaczony zbiór danych to **earthquake_data.csv**.

W zbiorze tym należało zmienić nazwy kolumn i przygotować tabele łączącą wiek, płeć i odpowiedź na pytanie **Do you think the "Big One" will occur in your lifetime?**

### Wczytanie danych

In [5]:
data = pd.read_csv(r"../Original Data/earthquake_data.csv")  # załadowanie danych 
data.tail(15)  # wyświetlenie pierwszych pięciu rekordów

,"In general, how worried are you about earthquakes?","How worried are you about the Big One, a massive, catastrophic earthquake?","Do you think the ""Big One"" will occur in your lifetime?",Have you ever experienced an earthquake?,"Have you or anyone in your household taken any precautions for an earthquake (packed an earthquake survival kit, prepared an evacuation plan, etc.)?",How familiar are you with the San Andreas Fault line?,How familiar are you with the Yellowstone Supervolcano?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region
998,Not so worried,Not so worried,Yes,"Yes, one or more minor ones",No,Very familiar,Not at all familiar,60,Female,"$25,000 to $49,999",East North Central
999,Not at all worried,Not at all worried,No,No,No,Not at all familiar,Somewhat familiar,30 - 44,Female,"$50,000 to $74,999",New England
1000,Not at all worried,Not so worried,No,No,No,Somewhat familiar,Not at all familiar,60,Female,"$50,000 to $74,999",Middle Atlantic
1001,Not so worried,Not so worried,Yes,"Yes, one or more major ones",No,Extremely familiar,Somewhat familiar,60,Female,"$75,000 to $99,999",South Atlantic
1002,Not at all worried,Not at all worried,No,"Yes, one or more major ones",No,Very familiar,Somewhat familiar,60,Male,"$75,000 to $99,999",Mountain
1003,Somewhat worried,Somewhat worried,Yes,"Yes, one or more minor ones",Yes,Somewhat familiar,Somewhat familiar,45 - 59,Male,"$50,000 to $74,999",Pacific
1004,Not at all worried,Not at all worried,No,No,No,Not at all familiar,Not at all familiar,18 - 29,Female,"$10,000 to $24,999",East North Central
1005,Not so worried,Not so worried,No,No,Yes,Somewhat familiar,Somewhat familiar,60,Female,"$200,000 and up",West North Central
1006,Not at all worried,Not at all worried,No,"Yes, one or more minor ones",No,Very familiar,Somewhat familiar,45 - 59,Male,"$75,000 to $99,999",East North Central
1007,Not at all worried,Not at all worried,No,No,No,Somewhat familiar,Somewhat familiar,60,Female,Prefer not to answer,New England
1008,Not at all worried,Not at all worried,No,"Yes, one or more minor ones",No,Very familiar,Not so familiar,60,Male,Prefer not to answer,Pacific
1009,Not so worried,Somewhat worried,No,"Yes, one or more major ones",Yes,Extremely familiar,Somewhat familiar,60,Female,"$50,000 to $74,999",Pacific
1010,Not so worried,Extremely worried,No,"Yes, one or more minor ones",No,Somewhat familiar,Somewhat familiar,30 - 44,Female,Prefer not to answer,Middle Atlantic
1011,Not at all worried,Not so worried,No,No,No,Somewhat familiar,Somewhat familiar,30 - 44,Female,"$50,000 to $74,999",East North Central
1012,Somewhat worried,Not so worried,No,"Yes, one or more minor ones",No,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df = pd.DataFrame({"Age": data["Age"], 
                   "Gender":data["What is your gender?"], 
                   "Answer": data["Do you think the \"Big One\" will occur in your lifetime?"]})

In [20]:

df.dropna().head(15)

        Age Gender Answer
0   18 - 29   Male     No
1   18 - 29   Male     No
2   18 - 29   Male     No
3   18 - 29   Male     No
4   18 - 29   Male    Yes
5   18 - 29   Male     No
7   18 - 29   Male     No
8   18 - 29   Male     No
9   18 - 29   Male     No
10  18 - 29   Male     No
11  18 - 29   Male     No
13  18 - 29   Male    Yes
14  18 - 29   Male     No
15  18 - 29   Male    Yes
16  18 - 29   Male     No

In [ ]:
age    Gender PositiveAnswer NegativeAnswer
18-29  Male   12             15
18-29  Female 10             23